// <auto-generated />
using System;
using ClosetCompanionApp.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClosetCompanionApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726055945_IntroduceOutfitGarmentJoinTable")]
    partial class IntroduceOutfitGarmentJoinTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClosetCompanionApp.Domain.Garment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceWebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Garments");
                });

            modelBuilder.Entity("ClosetCompanionApp.Domain.GeneratedOutfit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BasePhotoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("GeneratedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<string>("ResultImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BasePhotoId");

                    b.ToTable("GeneratedOutfits");
                });

            modelBuilder.Entity("ClosetCompanionApp.Domain.OutfitGarment", b =>
                {
                    b.Property<Guid>("GeneratedOutfitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GarmentId")
                        .HasColumnType("uuid");

                    b.HasKey("GeneratedOutfitId", "GarmentId");

                    b.HasIndex("GarmentId");

                    b.ToTable("OutfitGarments");
                });

            modelBuilder.Entity("ClosetCompanionApp.Domain.PosePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PoseType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PosePhoto");
                });

            modelBuilder.Entity("ClosetCompanionApp.Domain.GeneratedOutfit", b =>
                {
                    b.HasOne("ClosetCompanionApp.Domain.PosePhoto", null)
                        .WithMany()
                        .HasForeignKey("BasePhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClosetCompanionApp.Domain.OutfitGarment", b =>
                {
                    b.HasOne("ClosetCompanionApp.Domain.Garment", null)
                        .WithMany()
                        .HasForeignKey("GarmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClosetCompanionApp.Domain.GeneratedOutfit", null)
                        .WithMany()
                        .HasForeignKey("GeneratedOutfitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
